import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row mx-auto gap-5 font-mono p-3 w-fit mt-5">
          <div>About Me</div>
          <div>Experience</div>
          <div>Projects</div>
          <div>Other Stuff</div>
        </div>
        {children}
      </body>
    </html>
  );
}
