import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div className="flex flex-row mx-auto gap-5">
        <div>About Me</div>
        <div>Experience</div>
        <div>Projects</div>
        <div>Other Stuff</div>
      </div>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
